version: 2.1

jobs:
  docker_layer_caching:
    docker:
    - image: cimg/base:stable
    parallelism: 2
    steps:
    - checkout
    - run: which docker
    - run: docker -v
    - setup_remote_docker:
        version: 20.10.7
        docker_layer_caching: true
    - run:
        command: |
          while true; do
            sleep 1
            printf "\n\n$(date)\n"
            docker images ls -a
            echo "======"
          done
        background: true
    - run:
        name: Build a really docker image
        command: |          
          docker build -f Dockerfile --tag throwaway:$CIRCLE_BUILD_NUM .
    - run: docker version
  machine_dlc:
    machine:
      docker_layer_caching: true
    parallelism: 2
    steps:
    - run: which docker
    - run: docker -v
    - run:
        command: |
          while true; do
            sleep 1
            printf "\n\n$(date)\n"
            docker images ls -a
            echo "======"
          done
        background: true
    - run:
        name: Build a really docker image
        command: |
          docker images ls -a
          dockerfile=Dockerfile
          echo "FROM golang:1.16 AS builder" > $dockerfile
          echo "RUN echo hello" >> $dockerfile
          echo " " >> $dockerfile
          echo "FROM gcc:11.2.0" > $dockerfile
          echo "RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y   cmake   python3-pip   python3" >> $dockerfile
          echo "RUN pip3 install --upgrade conan" >> $dockerfile
          echo "RUN echo hello" >> $dockerfile
          docker build -f $dockerfile --tag throwaway:$CIRCLE_BUILD_NUM .
          docker images ls -a
          docker run --rm throwaway:$CIRCLE_BUILD_NUM
    - run: docker version
    
workflows:
  version: 2
  vm_jobs:
    jobs:
      - docker_layer_caching
      - machine_dlc
